name: Danger - pull request check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.1'
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('.github/Gemfile') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: '.github/Gemfile'
          danger_file: '.github/DangerFilePR'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}