name: Check for Missing Tests

on:
  pull_request:
    branches:
      - main # Or your primary branch

jobs:
  check_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Required for git diff

      - name: Get changed Go files
        id: changed-files
        run: |
          changed_files=$(git diff --name-only HEAD~1 | grep -E '\.go$' | grep -v '_test\.go$')
          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT

      - name: Check for missing tests
        if: ${{ steps.changed-files.outputs.changed_files != '' }}
        run: |
          changed_files="${{ steps.changed-files.outputs.changed_files }}"
          IFS=$'\n'
          for file in $changed_files; do
            test_file="${file/_test.go/.go}" #creates the test file name.
            test_file="${file/.go/_test.go}"
            if [[ ! -f "$test_file" ]]; then
              echo "::warning::Go file $file changed, but no corresponding test file $test_file found."
              exit 1 # Fail the action.
            elif ! git diff --name-only HEAD~1 | grep -q "${test_file}"; then
              echo "::warning::Go file $file changed, but corresponding test file $test_file not changed."
              exit 1 # Fail the action.
            fi
          done
