name: Danger Check

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: PR labeler
        uses: actions/labeler@v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yml"
          sync-labels: false
          dot: true

  danger:
    needs: [ labeler ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.1'
      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: '.github/Gemfile'
          danger_file: '.github/DangerFilePR'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}